// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions { 
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe7q4e4YGJ6hfIzjyj_0UxUz26QtVQqc4',
    appId: '1:973099676935:web:5214d1f8c8e4b8e14801a2',
    messagingSenderId: '973099676935',
    projectId: 'flutter01-a7b65',
    authDomain: 'flutter01-a7b65.firebaseapp.com',
    storageBucket: 'flutter01-a7b65.firebasestorage.app',
    measurementId: 'G-Q8RB0QCHN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU1_cr3ipc6Z6xcD6O1BT1p_cD6SdOW0o',
    appId: '1:973099676935:android:4ca67eded40c8d534801a2',
    messagingSenderId: '973099676935',
    projectId: 'flutter01-a7b65',
    storageBucket: 'flutter01-a7b65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKpAcbHhXeLE8LRaDKUG7znr5nPd49Sp0',
    appId: '1:973099676935:ios:d564113e3fe05a384801a2',
    messagingSenderId: '973099676935',
    projectId: 'flutter01-a7b65',
    storageBucket: 'flutter01-a7b65.firebasestorage.app',
    iosBundleId: 'com.example.fourthMHw5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKpAcbHhXeLE8LRaDKUG7znr5nPd49Sp0',
    appId: '1:973099676935:ios:d564113e3fe05a384801a2',
    messagingSenderId: '973099676935',
    projectId: 'flutter01-a7b65',
    storageBucket: 'flutter01-a7b65.firebasestorage.app',
    iosBundleId: 'com.example.fourthMHw5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe7q4e4YGJ6hfIzjyj_0UxUz26QtVQqc4',
    appId: '1:973099676935:web:33e5a6f12722c1df4801a2',
    messagingSenderId: '973099676935',
    projectId: 'flutter01-a7b65',
    authDomain: 'flutter01-a7b65.firebaseapp.com',
    storageBucket: 'flutter01-a7b65.firebasestorage.app',
    measurementId: 'G-KP32CSRD7W',
  );
}
